config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'bookmarks#index'
  resources :bookmarks
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  validates :title, :url, presence: true
  validates_format_of :url, with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/?.*)\z/

  belongs_to :site, optional: true
  has_many :bookmark_tags
  has_many :tags, through: :bookmark_tags do
    def cache_key
      [count(:updated_at), maximum(:updated_at)].map(&:to_i).join('-')
    end
  end
end

app/models/bookmark_tag.rb
# frozen_string_literal: true

class BookmarkTag < ApplicationRecord
  belongs_to :bookmark, touch: true
  belongs_to :tag
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
  validates :url, presence: true
  validates_format_of :url, with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/?.*)\z/
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :bookmark_tags
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit update destroy]

  # GET /bookmarks
  def index
    query = params[:q]
    @bookmarks = BookmarkFinder.search(query) if query
    @bookmarks ||= Bookmark.all.includes(:tags)
    @tags = Tag.all
  end

  # GET /bookmarks/1
  def show; end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit; end

  # POST /bookmarks
  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      call_tag_builder
      perform_site_bilder_job
      redirect_to root_path, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bookmarks/1
  def update
    if @bookmark.update(bookmark_params)
      call_tag_builder
      perform_site_bilder_job
      redirect_to root_path, notice: 'Bookmark was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookmarks/1
  def destroy
    perform_site_destroyer_job
    remove_associations_with_tags
    @bookmark.destroy
    redirect_to root_path, notice: 'Bookmark was successfully destroyed.'
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.fetch(:bookmark, {}).permit(:title, :url, :shortening)
  end

  def call_tag_builder
    TagBuilder.call(params[:tags], @bookmark.id)
  end

  def perform_site_bilder_job
    SiteBuilderJob.perform_later(@bookmark.url, @bookmark.id)
  end

  def perform_site_destroyer_job
    SiteDestroyerJob.perform_later(@bookmark.site_id, @bookmark.id)
  end

  def remove_associations_with_tags
    TagBuilder.new(nil, @bookmark.id).remove_old_associations
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/bookmarks/_bookmark.html.erb
<% cache [bookmark, bookmark.tags] do %>
  <tr>
    <td><%= bookmark.title %></td>
    <td><%= bookmark.shortening %></td>
    <td><%= link_to bookmark.url, bookmark.url, target: '_blank' %></td>
    <td>
      <% bookmark.bookmark_tags.each do |bookmark_tag| %>
        <% cache [bookmark_tag, tag] do %>
          <span class='tag'><%= bookmark_tag.tag.title %></span>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Delete', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, local: true) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag :title  %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>
  <div class="form-group">
    <%= label_tag :url  %>
    <%= form.text_field :url, class: 'form-control', placeholder: 'URL' %>
  </div>
  <div class="form-group">
    <%= label_tag :shortening  %>
    <%= form.text_field :shortening, class: 'form-control', placeholder: 'Shortening' %>
  </div>
  <div class="form-group">
    <%= label_tag :tags %>
    <%= text_field_tag :tags, params['tags'] || @bookmark.tags.map(&:title).join(','), id: 'tags', class: 'form-control' %>
    <p>* press Enter to add a new tag</p>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/bookmarks/_search.html.erb
<%= form_tag(root_path, method: :get, class: "form-inline search-form") do %>
  <div class="form-group">
    <%= text_field_tag 'q[term]', params[:q] ? params[:q][:term] : '', placeholder: "Search bookmarks", class: 'form-control' %>
    <%= submit_tag 'Search', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/bookmarks/_tag.html.erb
<% cache tag do %>
  <a href="<%= root_path(q: { tag: tag.title }) %>"><span class='tag'><%= tag.title %></span></a>
<% end %>

app/views/bookmarks/edit.html.erb
<h3>Editing Bookmark</h3>

<%= render 'form', bookmark: @bookmark %>

<div class='nav-button'>
  <%= link_to 'Back', root_path, class: 'btn btn-info' %>
</div>

app/views/bookmarks/index.html.erb
<h3><%= link_to 'Bookmarks', root_path %></h3>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<%= render partial: 'search' %>
<%= render partial: 'tag', collection: @tags, cached: true %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><b>Title</b></th>
      <th><b>Shortening</b></th>
      <th><b>URL</b></th>
      <th colspan='3'><b>Tags</b></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'bookmark', collection: @bookmarks, cached: true %>
  </tbody>
</table>

<div class='nav-button'>
  <%= link_to 'New Bookmark', new_bookmark_path, class: 'btn btn-info' %>
</div>

app/views/bookmarks/new.html.erb
<h3>New Bookmark</h3>

<%= render 'form', bookmark: @bookmark %>

<div class='nav-button'>
  <%= link_to 'Back', bookmarks_path, class: 'btn btn-info' %>
</div>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebBookmarks</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-1.12.4.min.js", integrity: "sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=", crossorigin: "anonymous" %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>